name=input("Enter your name : ")
eng_marks=int(input("Enter english marks :"))
maths_marks=int(input("Enter maths marks :"))
sci_marks=int(input("Enter science marks :"))
sum =(eng_marks+maths_marks+sci_marks)
avg=(sum/3)
print("---------------------------------")
print("Name of Student :",name)
print("English marks :",eng_marks)
print("Maths marks: ",maths_marks)
print("Science marks: ",sci_marks)
print("Average=",avg)
print("---CODE EXECUTED SUCCESSFULLY---")

