print("New File")
name=input("Enter your name : ")
eng_marks=input("Enter english marks :")
maths_marks=input("Enter maths marks :")
print("* Details of student *")
print("Name of Student :"+name)
print("English marks :"+eng_marks)
print("Maths marks: "+maths_marks)
print("---CODE EXECUTED SUCCESSFULLY---")